### ISSUE TITLE
Greek letter symbols shadowed with italic versions

### ISSUE THREAD

**Issue by jtassarotti** [vspinu/math-symbol-lists#10]
For old versions of this library, (v1.2.1 and earlier), when loading the symbol list with quail, typing  `\sigma` (and other Greek letters) used to default to non-italic versions of those letters.

It seems that in commit https://github.com/vspinu/math-symbol-lists/commit/1cf7e2885f3352f55852ee9eba26c7cb5a7cd74b all of the Greek letters are defined twice in the "mathalpha" symbol set. Once with the non-italic font, and then with italic font.

For my configuration, this has meant that after upgrading, `\sigma` will now default to the italic version (and I have to type `\upsigma` to get the non-italic version). Was it intentional to define things twice in this way? If so, is there an easy way to configure things so that `\sigma` will go back to picking the non-italic version?

For reference, I load the symbol lists as follows:
```
(quail-define-package "math" "UTF-8" "Ω" t)
(quail-define-rules ; add whatever extra rules you want to define here...

 ;; omitting a bunch of custom symbols
 ;; ...

 ;; subscripts and superscripts
 ("^^+" ?⁺) ("__+" ?₊) ("^^-" ?⁻)
 ("__0" ?₀) ("__1" ?₁) ("__2" ?₂) ("__3" ?₃) ("__4" ?₄)
 ("__5" ?₅) ("__6" ?₆) ("__7" ?₇) ("__8" ?₈) ("__9" ?₉)
)
(mapc (lambda (x)
        (if (cddr x)
            (quail-defrule (cadr x) (car (cddr x)))))
      (append math-symbol-list-basic math-symbol-list-extended))
```

**Comment by RalfJung** [comment]
For context, we are using these symbols in code, and all existing code uses σ. So if `\sigma` now emits a different symbol, this will lead to errors because the name does not match how it was declared.

**Comment by vspinu** [comment]
This package provides a list of symbols. The consumers of this package should take care of the sorting or deduplication. The default sorting in this package gives precedence to the non-italics version - he italics always follow the non-italics.

The [company-math](https://github.com/vspinu/company-math) does goes the easy way and deduplicates the codes. Hence this issue does not appear there. 

You should report this issue to the whatever package you are using for completion.
