### ISSUE TITLE
A few other sources of symbols

### ISSUE THREAD

**Issue by cpitclaudel** [vspinu/math-symbol-lists#2]
Hey @vspinu,

Continuing on our discussion, here are a few other sources:

* https://github.com/scim-im/scim-tables/blob/master/tables/additional/LaTeX.txt.in (though it's missing \land, \lor, etc). There's a Ubuntu bug report about that, at https://bugs.launchpad.net/ubuntu/+source/scim-tables/+bug/379206
* Emacs' very own TeX input method could be of interest too (`M-x describe-input-method TeX`). It includes `\iff`
* http://tug.ctan.org/info/latex2e-help-texinfo/latex2e.info has some information about \land
* The `src/conf/base.cfg` file of http://download.savannah.gnu.org/releases/elyxer/elyxer-1.2.5.tar.gz has plenty of mappings, including `\land` etc.
* https://www.cl.cam.ac.uk/~mgk25/ucs/examples/TeX.txt has this list of alternate names:
```
	≠ \ne or \neq	(same as \not=)
	≤ \le		(same as \leq)
	≥ \ge		(same as \geq)
	{ \{		(same as \lbrace)
	} \}		(same as \rbrace)
	→ \to		(same as \rightarrow)
	← \gets		(same as \leftarrow)
	∋ \owns		(same as \ni)
	∧ \land		(same as \wedge)
	∨ \lor		(same as \vee)
	¬ \lnot		(same as \neg)
	∣ \vert		(same as |)
	∥ \Vert		(same as |\)
```
* `org-mode` has an `org-entities` define which contains many mappings, too.

It seems that `\land`, `\lor` and a few others come from plain TeX; that's why they are not often on LaTeX list. Still, I think it would be very helpful to include them.

Let me know if I can help in any way!

**Comment by vspinu** [comment]
Thanks Clément. Thhis is very useful. The worst case I will just include those alternatives manually.

> It seems that \land, \lor and a few others come from plain TeX; that's why they are not often on LaTeX list. Still, I think it would be very helpful to include them.

Indeed. This is why I have two lists -basic and -extended. `-basic` needs to include all accepted commands by TeX. I want to keep the -extended one compatible with `unicode-math`. The LUCR list has annotations for synonyms like `= \to, = \tfun (oz),`. Some of them are plain LaTeX others are package related. We can try to parse those and have an extra list `math-symbols-synonyms`. In any case all LaTeX symbols must be part of `-basic`.

**Comment by cpitclaudel** [comment]
Thanks for the explanation :) Indeed, maybe a `math-symbols-synonyms` list would be nice :)
