### ISSUE TITLE
Squigly arrows

### ISSUE THREAD

**Issue by cpitclaudel** [vspinu/math-symbol-lists#3]
Hey @vspinu,

We currently map both `\rightsquigarrow` an `\rightwavearrow` to the same symbol, `↝`.
On the other hand, we map `\leftsquigarrow` and `\leftwavearrow` to different symbols, `⇜` and `↜`.

Should we fix `\rightsquigarrow` to map to `⇝`? It would be consistent with the name of the corresponding Unicode symbols (`RIGHT SQUIGGLE ARROW` and `RIGHT WAVE ARROW`).

Cheers,
Clément.

**Comment by vspinu** [comment]
This is a problem with -basic list. It maps `rigthsquigarrow` to wrong symbol. Both lists are merged and duplicates are removed. While this is easy to fix by reversing the order of lists in company-math I am considering to parse -basic list from LUCR database.

**Comment by cpitclaudel** [comment]
Ah, got it!

By the way, why does the `-extended` list have a different format from the `-basic` one? Is there a difference between the contents of the strings and the single characters?

Thanks for your work on this package!

**Comment by vspinu** [comment]
Those were compiled from different sources. But they have same format except for the last element is being absent in basic list. I will fix that as well.

There is no way to compile a comprehensive list of plain latex commands from LUCR database. So I just re-formated those a little bit and removed the AMS commands. Those are not part of plain LaTeX and, as you noticed, they are not always correct. 

I could use LUCR to generate aliases for plain latex. They are now part of basic list

```
    ;; extra aliases retrieved from LUCR
    ("bin" "\\land" 8743 "∧")
    ("bin" "\\lor" 8744 "∨")
    ("close" "\\rbrace" 125 "}")
    ("fence" "\\vert" 124 "|")
    ("fence" "\\Vert" 8214 "‖")
    ("open" "\\lbrace" 123 "{")
    ("ord" "\\mathdollar" 36 "$")
    ("ord" "\\lnot" 172 "¬")
    ("rel" "\\gets" 8592 "←")
    ("rel" "\\to" 8594 "→")
    ("rel" "\\owns" 8715 "∋")
    ("rel" "\\ne" 8800 "≠")
    ("rel" "\\le" 8804 "≤")
    ("rel" "\\ge" 8805 "≥"))
```

I have also generated a separate list of symbols for various latex packages `math-symbol-list-packages` contains those. Not sure how useful those are but might be used for specific completions or menu entries.

**Comment by cpitclaudel** [comment]
Beautiful work :) Many thanks.
