### ISSUE TITLE
Two more sources

### ISSUE THREAD

**Issue by cpitclaudel** [vspinu/math-symbol-lists#4]
Hey there,

These sources could be of interest as well:

* https://raw.githubusercontent.com/moebiuscurve/ibus-table-others/master/tables/latex.txt is the table that ibus-tables-latex uses.
* https://www.w3.org/2003/entities/2007xml/unicode.xml is a mapping apparently developed by W3C; it seems pretty comprehensive

Clément.

**Comment by vspinu** [comment]
Thanks. ibus one is very small. The W3C contains less symbols than unicode-math package, but it's definitely interesting because it maps to  a bunch of systems; latex and unicode-math are two of them.

I have added it to a list of source inside the package comments header. Thanks.
