### ISSUE TITLE
Support for subscripts?

### ISSUE THREAD

**Issue by cpitclaudel** [vspinu/math-symbol-lists#5]
Hi @vspinu,

Are we interested in subscripts and superscripts? They are supported by the TeX input method and IBus.

If so, here's a quick script to get a decent collection of them.

``` elisp
  (mapcar (lambda (c)
            (pcase (get-char-code-property c 'decomposition)
              (`(super ,char) (princ (format "%c: \\^%c\n" c char)))
              (`(sub ,char) (princ (format "%c: \\_%c\n" c char)))
              (_ (princ (unless t (format "%c: Other\n" c))))))
          (string-to-list "ª²³¹ºəʰʱʲʳʴʵʶʷʸˠˡˢˣᴬᴭᴮᴯᴰᴱᴲᴳᴴᴵᴶᴷᴸᴹᴺᴻᴼᴽᴾᴿᵀᵁᵂᵃᵄᵅᵆᵇᵈᵉᵊᵋᵌᵍᵎᵏᵐᵑᵒᵓᵔᵕᵖᵗᵘᵙᵚᵛᵜᵝᵞᵟᵠᵡᵢᵣᵤᵥᵦᵧᵨᵩᵪᵸᶛᶜᶝᶞᶟᶠᶡᶢᶣᶤᶥᶦᶧᶨᶩᶪᶫᶬᶭᶮᶯᶰᶱᶲᶳᶴᶵᶶᶷᶸᶹᶺᶻᶼᶽᶾᶿ⁰ⁱ⁴⁵⁶⁷⁸⁹⁺⁻⁼⁽⁾ⁿ₀₁₂₃₄₅₆₇₈₉₊₋₌₍₎ₐₑₒₓₔₕₖₗₘₙₚₛₜⱼⱽ"))
```

Clément.

**Comment by vspinu** [comment]
This is interesting. Completion can be triggered by ^ and _ directly instead of \.  

Where did you get that string from? Is it a comprehensive listing of uperscripts and subscripts?

**Comment by cpitclaudel** [comment]
Uh, did I really not answer this? :/
I got it from the wikipedia page on [unicode subscripts](https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts) :)

**Comment by tpapp** [comment]
Bumping this issue (because I really need them in Julia). @vspinu, if I wanted to make a PR, how should I go about it? Should it go into `msl-build.el` and generate something (how?) or `math-symbol-lists.el`?

**Comment by tpapp** [comment]
Realizing that completing sub- and superscripts would require some fundamental changes to the completing backends, I wrote another one company backend:
https://github.com/tpapp/company-unicode-subsuper

Usage is very natural and does not interfere with libraries that use `math-symbol-lists`, eg in company-mode, `_1` completes to `₁`, `^+` to `⁺`, `^theta` to `ᶿ`, etc.

**Comment by vspinu** [comment]
I have added now the subscript and superscript lists to math-symbol-list and incorporated subsups into company-math-unicode backed. I do believe that this functionality should be in one package and under same symbol list to avoid bothering users with extra backends for very related functionality.

@tpapp, you were right. This change required quite  rewrite of the company-math.
