### ISSUE TITLE
epsilon vs lunate epsilon

### ISSUE THREAD

**Issue by tpapp** [vspinu/math-symbol-lists#6]
Now that I am using  Unicode symbols a lot in Julia I found that I favor ε (`\varepsilon`) much more than ϵ (`\epsilon`) since the latter looks like a smaller version of ∈ (`\in`) in many fonts.

I know that TeX chose the lunate form for `\epsilon`, but I am wondering if there could be an option for exchanging them.

**Comment by vspinu** [comment]
> but I am wondering if there could be an option for exchanging them.

Not as part of the package. 

Do you want to change it only for company completion? Then the following will do:

```el
(setf (car (member "epsilon" company-math--symbols))
      (propertize "epsilon" :symbol "ε"))
```

If you want to change it for all the packages that rely on `math-symbol-lists` then you need to place the following before package initialization:

```el

(with-eval-after-load "math-symbol-lists"
  (let ((eps (rassoc-if (lambda (el) (equal "\\epsilon" (car el)))
                        math-symbol-list-basic)))
    (setf (nth 2 eps) #X3B5)))
```

**Comment by vspinu** [comment]
The company-math was rewriten slightly to allow for sub(super)scripts. So the first woraround should now be 

```el
(setf (car (member "\\epsilon" company-math--symbols))
      (propertize "epsilon" :symbol "ε"))
```

the second workaround stays the same.
