### ISSUE TITLE
\square not included?

### ISSUE THREAD

**Issue by beta-ziliani** [vspinu/math-symbol-lists#7]
What is the reason for some symbols to not be included, like \square and \Box? Is there a way to have them? Thanks!

**Comment by vspinu** [comment]
Good question. The convention is to use the same names as the one in `http://mirror.ctan.org/help/Catalogue/entries/unicode-math.html`, so \\square would be \\mdwhtsquare. 

Not entirely sure how to proceed here. If I include both unicode-math and the name used in a particular latex package (in your case `amsmath`) then there might be conflicts.

**Comment by vspinu** [comment]
Hmm, I see now that [LUCR](http://milde.users.sourceforge.net/LUCR/Math/) is no longer supplying unicode-math translation as part of their database but rather has a separate [diff](http://milde.users.sourceforge.net/LUCR/Math/unicode-math-diff.html) page for it. 

Will have to think of how to move to new format on this occasion I guess.
