### ISSUE TITLE
could it be possible to have fuzzy selection?

### ISSUE THREAD

**Issue by beta-ziliani** [vspinu/math-symbol-lists#8]
For instance, to be able to write \wafb and get the option \whitearrowupfrombar.

**Comment by vspinu** [comment]
I presume this is for company-mode right? Then it should go to [company-math](https://github.com/vspinu/company-math/issues) but it's out of scope even there. 

There are fuzzy completion solutions for company ([this](https://github.com/PythonNut/company-flx) and [this](https://github.com/jcs-elpa/company-fuzzy). If you could figure the setup with any of them I would be more than happy to add it to the readme or add required support if needed.

**Comment by vspinu** [comment]
This is not
