### ISSUE TITLE
What's the meaning of "storage" package?

### ISSUE THREAD

**Issue by hongyi-zhao** [vspinu/math-symbol-lists#9]
The [readme.md](https://github.com/vspinu/math-symbol-lists/blob/master/readme.md) of this package said that:

```
This is a "storage" package used by completion engines such as company-math.el and ac-math.el.

Defined (a)lists are:

math-symbol-list-basic math-symbol-list-extended math-symbol-list-packages math-symbol-list-latex-commands
```
But what's the mean of "storage" package here? Does it mean that this package will be automatically included in other caller packages and thus is needless to install separately, i.e., through something like the following?

`(use-package math-symbol-lists)
`

Regards,
HY

**Comment by vspinu** [comment]
"storage" means it stores those lists and that all it does, no functionality. 

> it mean that this package will be automatically included in other caller

This package is a dependency of other packages, so indeed. It will be automatically installed and you don't need to install it separately.
